### PR TITLE
feat: replace DS vertx sample with Che Java Guestbook sample

### PR DESCRIPTION
**Pull request by mkuznyetsov**
Since Devspace Sample "vertx-http-example" id dropped from DS release cycle, we would replace it with another Java sample from Che Sample "Java Guestbook"

### CODE REVIEW

**Comment by nickboldt** [comment]
Why wouldn't we pick a different downstream java sample? https://github.com/redhat-developer/devspaces/tree/devspaces-3-rhel-8/dependencies/che-devfile-registry/devfiles/ we have lombok and quarkus too. Just curious...

**Comment by svor** [comment]
- The site already contains [quarkus sample](https://github.com/eclipse-che/che-website/blob/main/src/lib/try/TryOnline.svelte#L65)
- About lombok, it can be an option, but as for me it's not very informative - contains only [build command](https://github.com/devspaces-samples/lombok-project-sample/blob/devspaces-3-rhel-8/devfile.yaml#L21)

**Comment by nickboldt** [comment]
should we move the sample downstream?

**Comment by svor** [comment]
If we want more samples in downstream, we can :)

**Comment by nickboldt** [comment]
well, it would be more downstream, less upstream :D

**Pull request merged**
