### PR TITLE
[DO NOT MERGE] feat: use .NET sample from registry.devfile.io

### PR DESCRIPTION
**Pull request by ibuziuk**
https://workspaces.openshift.com#https://registry.devfile.io/devfiles/dotnet60/1.0.3&storageType=ephemeral

Screenshot 2024-04-16 at 18 05 27

### CODE REVIEW

**Comment by ibuziuk** [comment]
@olexii4 @akurinnoy folks, why it does not work?

**Review by olexii4 — APPROVED** [review]

**Comment by olexii4** [comment]
@ibuziuk It is an expected behavior. Adding the "https://registry.devfile.io/" as an external Devfile registry will fix the problem because  CHE-dashboard uses different APIs to resolve the factory from the URL from the external Devfile registry.

**Comment by ibuziuk** [comment]
@olexii4 hmm.. but why it does not work OOTB? This should work on instances that do not have "https://registry.devfile.io/" enabled

**Comment by olexii4** [comment]
> @olexii4 hmm.. but why it does not work OOTB? This should work on instances that do not have "https://registry.devfile.io/" enabled
> 
> https://registry.devfile.io/devfiles/dotnet60/1.0.3 is just a link to raw devfile
It happens because che-server can't resolve factory files from unknown resources:

```{che-server}/swagger/#/factory/resolveFactory```

Знімок екрана 2024-04-17 о 11 25 28

**Comment by ibuziuk** [comment]
@olexii4 sorry, I do not understand

https://registry.devfile.io/devfiles/dotnet60/1.0.3  is a raw devfile URL which should always work and can be hosted anywhere

**Comment by akurinnoy** [comment]
@ibuziuk, currently, the dashboard fetches raw devfiles if they are located in a registry (known to the dashboard). Otherwise, it uses the che-server API to resolve that URL.

**Comment by olexii4** [comment]
> @olexii4 sorry, I do not understand
> 
> https://registry.devfile.io/devfiles/dotnet60/1.0.3 is a raw Devfile URL that should always work and can be hosted anywhere

In that case, it is a well-known bug of che-server.

**Comment by ibuziuk** [comment]
@olexii4 @akurinnoy why not have a common mechanism for handling raw devfiles no matter where hosted? I'm just trying to understand impl detail right now e.g. why for the dashboard it matters from where the raw URL is coming from 🤷

**Comment by akurinnoy** [comment]
@ibuziuk, it would be great to have a mechanism like that on the dashboard.

I opened an issue for the improvement https://github.com/eclipse-che/che/issues/22927

**Comment by ibuziuk** [comment]
@vinokurig should we use some URL parameter to make it work?

**Comment by vinokurig** [comment]
Indeed, it is expected that RAW url without `yaml` or `.yaml` ending will not work because we can not distinguish the url from a git repository url in another way yet.
My proposal is to open a ticket to support RAW urls with any name.

**Comment by ibuziuk** [comment]
@vinokurig is it possible to make it work now using URL parameter df or smth. else?

**Comment by vinokurig** [comment]
Unfortunately no, we are using a strict pattern for that: https://github.com/eclipse-che/che-server/blob/858a12b3ff50e5d890881ac7a40c48608d4c5ea7/wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/RawDevfileUrlFactoryParameterResolver.java#L44

**Comment by ibuziuk** [comment]
ok, weird 
we need to fix it - https://eclipse.dev/che/docs/stable/end-user-guide/url-parameter-for-the-devfile-file-name/

**Comment by vinokurig** [comment]
https://eclipse.dev/che/docs/stable/end-user-guide/url-parameter-for-the-devfile-file-name/ does not control the RAW urls, it just defines the yaml name in a git repository if it is not conventional (.devfile / devfile).

**Pull request merged**
